server:
  port: 8000

zuul:
  ignoredServices: '*'
  routes:
    gms:
      path: /gms/**
      serviceId: gms
      stripPrefix: false


endpoints:
  routes:
    sensitive: false
#  trace:
#    sensitive: false

eureka:
  client:
    serviceUrl:
      #defaultZone: http://172.18.0.2:8761/eureka
      default-zone: http://localhost:8761/eureka
      
